In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import platform
from scipy.stats import chi2_contingency
import pandas as pd

pd.set_option('display.float_format',"{:.2f}".format)

# OS에 따라 다른 폰트 지정
if platform.system() == 'Darwin':   # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
elif platform.system() == 'Windows':  # Windows
    plt.rcParams['font.family'] = 'Malgun Gothic'
else:  # Linux (예: Colab, Ubuntu)
    plt.rcParams['font.family'] = 'NanumGothic'

In [2]:
df = pd.read_csv("Courses.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641138 entries, 0 to 641137
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   index              641138 non-null  int64
 1   course_id          641138 non-null  object
 2   userid_DI          641138 non-null  object
 3   registered         641138 non-null  int64
 4   viewed             641138 non-null  int64
 5   explored           641138 non-null  int64
 6   certified          641138 non-null  int64
 7   final_cc_cname_DI  641138 non-null  object
 8   LoE_DI             535130 non-null  object
 9   YoB                544533 non-null  float64
 10  gender             554332 non-null  object
 11  grade              592766 non-null  object
 12  start_time_DI      641138 non-null  object
 13  last_event_DI      462184 non-null  object
 14  nevents            441987 non-null  float64
 15  ndays_act          478395 non-null  float64
 16  nplay_video        183608 non-null  float64
 17  nchapters          382385 non-null  float64
 18  nforum_posts       641138 non-null  int64
 19  roles              0 non-null       float64
 20  incomplete_flag    100161 non-null  float64
dtypes: float64(7), int64(6), object(8)
memory usage: 102.7+ MB

In [3]:
df.columns = df.columns.str.lower()

In [4]:
df.columns

Index(['index', 'course_id', 'userid_di', 'registered', 'viewed', 'explored',
       'certified', 'final_cc_cname_di', 'loe_di', 'yob', 'gender', 'grade',
       'start_time_di', 'last_event_di', 'nevents', 'ndays_act', 'nplay_video',
       'nchapters', 'nforum_posts', 'roles', 'incomplete_flag'],
      dtype='object')

In [5]:
df['final_cc_cname_di'].value_counts()

final_cc_cname_di
United States                             184240
India                                      88696
Unknown/Other                              82029
Other Europe                               40377
Other Africa                               23897
United Kingdom                             22131
Brazil                                     17856
Other Middle East/Central Asia             17325
Other South Asia                           12992
Canada                                     12738
Pakistan                                   10824
Russian Federation                         10432
Spain                                      10003
Other South America                         9916
Egypt                                       9286
Germany                                     8074
Nigeria                                     7483
Other East Asia                             6446
Australia                                   6419
Mexico                                      5638
Philippines                                 5374
Poland                                      5226
China                                       5170
Greece                                      5162
Colombia                                    4803
France                                      4700
Other North & Central Amer., Caribbean      4434
Ukraine                                     4100
Morocco                                     3966
Indonesia                                   3410
Bangladesh                                  3182
Japan                                       2270
Portugal                                    2193
Other Oceania                                346
Name: count, dtype: int64

In [6]:
df['course_id'].value_counts()

course_id
HarvardX/CS50x/2012            169621
MITx/6.00x/2012_Fall            66731
MITx/6.00x/2013_Spring          57715
HarvardX/ER22x/2013_Spring      57406
HarvardX/PH207x/2012_Fall       41592
MITx/6.002x/2012_Fall           40811
HarvardX/PH278x/2013_Spring     39602
MITx/8.02x/2013_Spring          31048
HarvardX/CB22x/2013_Spring      30002
MITx/14.73x/2013_Spring         27870
MITx/6.002x/2013_Spring         22235
MITx/7.00x/2013_Spring          21009
MITx/3.091x/2012_Fall           14215
MITx/8.MReV/2013_Summer          9477
MITx/3.091x/2013_Spring          6139
MITx/2.01x/2013_Spring           5665
Name: count, dtype: int64

In [7]:
df.groupby('loe_di')['explored'].mean()

loe_di
Bachelor's            0.05
Doctorate             0.07
Less than Secondary   0.07
Master's              0.07
Secondary             0.05
Name: explored, dtype: float64

In [8]:
df.groupby(['course_id','loe_di'])['index'].agg(['count'])

                                                count
course_id                  loe_di
HarvardX/CB22x/2013_Spring Bachelor's            9896
                           Doctorate             1076
                           Less than Secondary    666
                           Master's              6857
                           Secondary             7028
...                                               ...
MITx/8.MReV/2013_Summer    Bachelor's            2257
                           Doctorate               44
                           Less than Secondary    328
                           Master's               896
                           Secondary             3753

[80 rows x 1 columns]

In [9]:
df['certified'].value_counts()

certified
0    623451
1     17687
Name: count, dtype: int64

In [10]:
print(df['viewed'].value_counts(normalize=True) * 100)
print(df['explored'].value_counts(normalize=True) * 100)
print(df['certified'].value_counts(normalize=True) * 100)

viewed
1   62.43
0   37.57
Name: proportion, dtype: float64
explored
0   93.81
1    6.19
Name: proportion, dtype: float64
certified
0   97.24
1    2.76
Name: proportion, dtype: float64

In [11]:
df_crosstab = pd.crosstab(
    [df['viewed'], df['explored'], df['certified']],
    columns = 'count',
    normalize = 'all') * 100

df_crosstab

col_0                      count
viewed explored certified
0      0        0          37.57
       1        0           0.00
1      0        0          56.13
                1           0.11
       1        0           3.54
                1           2.65

In [12]:
441987/641137

0.6893799609131902

In [13]:
df['grade'].value_counts()
df['grade'] = pd.to_numeric(df['grade'], errors='coerce')
df2 = df.loc[df['grade']>0]

df2['grade'].count()

np.int64(74345)

In [14]:
74345/641137

509393/641137

0.794515056844325

In [15]:
df0 = df.loc[df['grade']==0]

df0['grade'].count()

np.int64(509393)

In [16]:
df_nforum = df.loc[df['nforum_posts'] > 0]
df_nforum.groupby('nforum_posts')['certified'].agg(['count','mean'])

              count  mean
nforum_posts
1              4996  0.22
2              1496  0.26
3               483  0.32
4               197  0.35
5               129  0.42
6                88  0.58
7                15  0.40
8                18  0.61
9                10  0.90
12                5  0.40
13               13  0.62
15                5  1.00
20                6  1.00

In [17]:
df_nforum.groupby('final_cc_cname_di')['nforum_posts'].agg(['count','mean']).sort_values(by='mean', ascending=False)

                                        count  mean
final_cc_cname_di
United States                            3735  1.79
Mexico                                     42  1.71
Other South America                        58  1.69
United Kingdom                            224  1.59
Other Europe                              400  1.55
India                                    2118  1.53
Philippines                                10  1.50
Russian Federation                         75  1.41
Spain                                      76  1.37
Poland                                     14  1.36
Pakistan                                   56  1.36
Colombia                                   70  1.34
Brazil                                     91  1.33
Canada                                     71  1.15
Other Africa                              250  1.14
Bangladesh                                  5  1.00
Greece                                     44  1.00
Germany                                    26  1.00
Egypt                                      10  1.00
Other East Asia                            13  1.00
Other North & Central Amer., Caribbean      6  1.00
Other Middle East/Central Asia             31  1.00
Nigeria                                     6  1.00
Other South Asia                           30  1.00

In [18]:
forum = df.groupby('final_cc_cname_di')['nforum_posts'].agg(['count', 'mean'])
forum['active_rate'] = df.groupby('final_cc_cname_di')['nforum_posts'].apply(lambda x: (x > 0).mean() * 100)
forum

                                         count  mean  active_rate
final_cc_cname_di
Australia                                 6419  0.00         0.00
Bangladesh                                3182  0.00         0.16
Brazil                                   17856  0.01         0.51
Canada                                   12738  0.01         0.56
China                                     5170  0.00         0.00
Colombia                                  4803  0.02         1.46
Egypt                                     9286  0.00         0.11
France                                    4700  0.00         0.00
Germany                                   8074  0.00         0.32
Greece                                    5162  0.01         0.85
India                                    88696  0.04         2.39
Indonesia                                 3410  0.00         0.00
Japan                                     2270  0.00         0.00
Mexico                                    5638  0.01         0.74
Morocco                                   3966  0.00         0.00
Nigeria                                   7483  0.00         0.08
Other Africa                             23897  0.01         1.05
Other East Asia                           6446  0.00         0.20
Other Europe                             40377  0.02         0.99
Other Middle East/Central Asia           17325  0.00         0.18
Other North & Central Amer., Caribbean    4434  0.00         0.14
Other Oceania                              346  0.00         0.00
Other South America                       9916  0.01         0.58
Other South Asia                         12992  0.00         0.23
Pakistan                                 10824  0.01         0.52
Philippines                               5374  0.00         0.19
Poland                                    5226  0.00         0.27
Portugal                                  2193  0.00         0.00
Russian Federation                       10432  0.01         0.72
Spain                                    10003  0.01         0.76
Ukraine                                   4100  0.00         0.00
United Kingdom                           22131  0.02         1.01
United States                           184240  0.04         2.03
Unknown/Other                            82029  0.00         0.00

In [19]:
df.groupby('nforum_posts')['certified'].agg(['count','mean'])

               count  mean
nforum_posts
0             633677  0.02
1               4996  0.22
2               1496  0.26
3                483  0.32
4                197  0.35
5                129  0.42
6                 88  0.58
7                 15  0.40
8                 18  0.61
9                 10  0.90
12                 5  0.40
13                13  0.62
15                 5  1.00
20                 6  1.00

In [20]:
df['nchapters'].describe()

count   382385.00
mean         3.63
std          4.49
min          1.00
25%          1.00
50%          2.00
75%          4.00
max         48.00
Name: nchapters, dtype: float64

In [21]:
df['nchapters'].isna().sum()

np.int64(258753)

In [22]:
df_nchapters = df.loc[df['nchapters'] > 0]
df_nchapters.count()

index                382385
course_id            382385
userid_di            382385
registered           382385
viewed               382385
explored             382385
certified            382385
final_cc_cname_di    382385
loe_di               315036
yob                  320069
gender               326155
grade                351884
start_time_di        382385
last_event_di        313275
nevents              309817
ndays_act            318632
nplay_video          182477
nchapters            382385
nforum_posts         382385
roles                     0
incomplete_flag       72568
dtype: int64

In [23]:
641137-382385

258752

In [24]:
total = len(df)

na_pct = df['grade'].isna().mean() * 100
zero_pct = (df['grade'] == 0).mean() * 100
pos_pct = (df['grade'] > 0).mean() * 100
neg_pct = (df['grade'] < 0).mean() * 100

print(f'결측: {na_pct:.2f}%')
print(f'0: {zero_pct:.2f}%')
print(f'0초과: {pos_pct:.2f}%')
print(f'0미만: {neg_pct:.2f}%')
print(f'합계: {na_pct + zero_pct + pos_pct + neg_pct:.2f}%')

결측: 8.95%
0: 79.45%
0초과: 11.60%
0미만: 0.00%
합계: 100.00%

In [25]:
df.info()
df['nforum_posts'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641138 entries, 0 to 641137
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   index              641138 non-null  int64
 1   course_id          641138 non-null  object
 2   userid_di          641138 non-null  object
 3   registered         641138 non-null  int64
 4   viewed             641138 non-null  int64
 5   explored           641138 non-null  int64
 6   certified          641138 non-null  int64
 7   final_cc_cname_di  641138 non-null  object
 8   loe_di             535130 non-null  object
 9   yob                544533 non-null  float64
 10  gender             554332 non-null  object
 11  grade              583738 non-null  float64
 12  start_time_di      641138 non-null  object
 13  last_event_di      462184 non-null  object
 14  nevents            441987 non-null  float64
 15  ndays_act          478395 non-null  float64
 16  nplay_video        183608 non-null  float64
 17  nchapters          382385 non-null  float64
 18  nforum_posts       641138 non-null  int64
 19  roles              0 non-null       float64
 20  incomplete_flag    100161 non-null  float64
dtypes: float64(8), int64(6), object(7)
memory usage: 102.7+ MB

nforum_posts
0     633677
1       4996
2       1496
3        483
4        197
5        129
6         88
8         18
7         15
13        13
9         10
20         6
12         5
15         5
Name: count, dtype: int64

In [26]:
total = len(df)

zero_pos = (df['nforum_posts'] == 0).mean() * 100
pos_pos = (df['nforum_posts'] > 0).mean() * 100

print(f'0: {zero_pos:.2f}%')
print(f'0초과: {pos_pos:.2f}%')

0: 98.84%
0초과: 1.16%

In [27]:
df['nplay_video'].value_counts()

nplay_video
1.00       16968
2.00       11000
3.00        8371
4.00        6995
5.00        5992
           ...
1949.00        1
2036.00        1
1762.00        1
2096.00        1
2292.00        1
Name: count, Length: 2728, dtype: int64

In [28]:
df['nplay_video'].map(type).value_counts()

nplay_video
<class 'float'>    641138
Name: count, dtype: int64

In [29]:
z1 = (df['nplay_video'] == 0).mean() * 100
z2 = (df['nplay_video'] > 0).mean() * 100

print(f'0: {z1:.2f}%')
print(f'0초과: {z2:.2f}%')

z3 = (df['nplay_video'] > 0).sum()
print(z3)

z4 = (df['nplay_video'] > 0).sum()
print(z4)

0: 0.00%
0초과: 28.64%
183608
183608

In [30]:
633677/641137

0.9883644213327261

In [31]:
df.isnull().mean() * 100

index                 0.00
course_id             0.00
userid_di             0.00
registered            0.00
viewed                0.00
explored              0.00
certified             0.00
final_cc_cname_di     0.00
loe_di               16.53
yob                  15.07
gender               13.54
grade                 8.95
start_time_di         0.00
last_event_di        27.91
nevents              31.06
ndays_act            25.38
nplay_video          71.36
nchapters            40.36
nforum_posts          0.00
roles               100.00
incomplete_flag      84.38
dtype: float64

In [32]:
df.groupby('loe_di')['certified'].agg(['count','mean'])

                      count  mean
loe_di
Bachelor's           219768  0.02
Doctorate             13387  0.03
Less than Secondary   14092  0.03
Master's             118189  0.04
Secondary            169694  0.02

In [33]:
df['final_cc_cname_di'].value_counts()

final_cc_cname_di
United States                             184240
India                                      88696
Unknown/Other                              82029
Other Europe                               40377
Other Africa                               23897
United Kingdom                             22131
Brazil                                     17856
Other Middle East/Central Asia             17325
Other South Asia                           12992
Canada                                     12738
Pakistan                                   10824
Russian Federation                         10432
Spain                                      10003
Other South America                         9916
Egypt                                       9286
Germany                                     8074
Nigeria                                     7483
Other East Asia                             6446
Australia                                   6419
Mexico                                      5638
Philippines                                 5374
Poland                                      5226
China                                       5170
Greece                                      5162
Colombia                                    4803
France                                      4700
Other North & Central Amer., Caribbean      4434
Ukraine                                     4100
Morocco                                     3966
Indonesia                                   3410
Bangladesh                                  3182
Japan                                       2270
Portugal                                    2193
Other Oceania                                346
Name: count, dtype: int64

In [34]:
82029/641137

0.12794301373965314

In [35]:
df00 = df.loc[df['final_cc_cname_di'] == 'United States']

In [36]:
print(df00['certified'].mean() * 100)
print(df00['explored'].mean() * 100)
print(df00['viewed'].mean() * 100)
print(df00['nforum_posts'].mean() * 100)

2.3784194528875378
5.499348675640469
63.7559704732957
3.6333043855840206

In [37]:
# "하는 중" 인 사람들이기때문에 결과인 certified 서티파이드.. 가 없을걸요?


df111 = df.loc[df['last_event_di'].isna()]
df111.groupby('certified')['certified'].agg(['count'])

            count
certified
0          178942
1              12

In [38]:
df111[(df111['incomplete_flag'] == 1) & (df111['certified'] == 1)].head(13)

,index,course_id,userid_di,registered,viewed,explored,certified,final_cc_cname_di,loe_di,yob,...,grade,start_time_di,last_event_di,nevents,ndays_act,nplay_video,nchapters,nforum_posts,roles,incomplete_flag
106843,106843,HarvardX/CS50x/2012,MHxPC130306856,1,1,1,1,Unknown/Other,Doctorate,1968.00,...,1.00,2012-11-30,NaN,NaN,NaN,NaN,12.00,0,NaN,1.00
144691,144691,HarvardX/PH207x/2012_Fall,MHxPC130033009,1,1,1,1,Other South Asia,Master's,1975.00,...,0.96,2012-10-17,NaN,NaN,NaN,NaN,15.00,0,NaN,1.00
213275,213275,HarvardX/PH278x/2013_Spring,MHxPC130522075,1,1,1,1,Unknown/Other,Secondary,1993.00,...,0.81,2013-03-17,NaN,NaN,NaN,NaN,10.00,0,NaN,1.00
252887,252887,HarvardX/PH278x/2013_Spring,MHxPC130410256,1,1,1,1,Other South Asia,Secondary,1992.00,...,0.81,2013-03-01,NaN,NaN,NaN,NaN,9.00,0,NaN,1.00
319145,319145,HarvardX/ER22x/2013_Spring,MHxPC130328116,1,1,1,1,Unknown/Other,Secondary,1994.00,...,0.69,2013-06-23,NaN,NaN,NaN,NaN,31.00,0,NaN,1.00
325969,325969,HarvardX/ER22x/2013_Spring,MHxPC130095114,1,1,0,1,Unknown/Other,Secondary,1993.00,...,1.00,2013-07-22,NaN,NaN,NaN,NaN,8.00,0,NaN,1.00
396575,396575,MITx/6.00x/2012_Fall,MHxPC130292274,1,1,1,1,Unknown/Other,NaN,NaN,...,0.60,2012-08-13,NaN,NaN,NaN,NaN,17.00,0,NaN,1.00
462248,462248,MITx/6.00x/2012_Fall,MHxPC130383454,1,1,1,1,Unknown/Other,Secondary,1993.00,...,0.63,2012-10-01,NaN,NaN,NaN,NaN,9.00,0,NaN,1.00
514799,514799,MITx/6.002x/2013_Spring,MHxPC130276145,1,1,1,1,India,Secondary,1992.00,...,0.77,2012-12-27,NaN,NaN,NaN,NaN,17.00,1,NaN,1.00
547604,547604,MITx/7.00x/2013_Spring,MHxPC130043740,1,1,1,1,Unknown/Other,Bachelor's,1989.00,...,0.69,2013-03-12,NaN,NaN,NaN,NaN,13.00,0,NaN,1.00
555757,555757,MITx/7.00x/2013_Spring,MHxPC130074389,1,1,1,1,Unknown/Other,Master's,1986.00,...,0.74,2013-03-12,NaN,NaN,NaN,NaN,16.00,0,NaN,1.00
586586,586586,MITx/14.73x/2013_Spring,MHxPC130333390,1,1,1,1,Unknown/Other,Secondary,1991.00,...,0.70,2013-03-09,NaN,NaN,NaN,NaN,10.00,0,NaN,1.00

In [39]:
df1111 = df.loc[df['explored']==0]
df1111.groupby('certified')['certified'].agg(['count'])

            count
certified
0          600762
1             690

In [40]:
df['final_cc_cname_di'].value_counts()

final_cc_cname_di
United States                             184240
India                                      88696
Unknown/Other                              82029
Other Europe                               40377
Other Africa                               23897
United Kingdom                             22131
Brazil                                     17856
Other Middle East/Central Asia             17325
Other South Asia                           12992
Canada                                     12738
Pakistan                                   10824
Russian Federation                         10432
Spain                                      10003
Other South America                         9916
Egypt                                       9286
Germany                                     8074
Nigeria                                     7483
Other East Asia                             6446
Australia                                   6419
Mexico                                      5638
Philippines                                 5374
Poland                                      5226
China                                       5170
Greece                                      5162
Colombia                                    4803
France                                      4700
Other North & Central Amer., Caribbean      4434
Ukraine                                     4100
Morocco                                     3966
Indonesia                                   3410
Bangladesh                                  3182
Japan                                       2270
Portugal                                    2193
Other Oceania                                346
Name: count, dtype: int64

# 여기부터 분석 시작

In [41]:
df['final_cc_cname_di'].value_counts(normalize=True) * 100

final_cc_cname_di
United States                            28.74
India                                    13.83
Unknown/Other                            12.79
Other Europe                              6.30
Other Africa                              3.73
United Kingdom                            3.45
Brazil                                    2.79
Other Middle East/Central Asia            2.70
Other South Asia                          2.03
Canada                                    1.99
Pakistan                                  1.69
Russian Federation                        1.63
Spain                                     1.56
Other South America                       1.55
Egypt                                     1.45
Germany                                   1.26
Nigeria                                   1.17
Other East Asia                           1.01
Australia                                 1.00
Mexico                                    0.88
Philippines                               0.84
Poland                                    0.82
China                                     0.81
Greece                                    0.81
Colombia                                  0.75
France                                    0.73
Other North & Central Amer., Caribbean    0.69
Ukraine                                   0.64
Morocco                                   0.62
Indonesia                                 0.53
Bangladesh                                0.50
Japan                                     0.35
Portugal                                  0.34
Other Oceania                             0.05
Name: proportion, dtype: float64

In [42]:
# 강의id로 파생컬럼 만들기

df_f = df.copy()

df_f[['institution','course_code','a']] = df_f['course_id'].str.split('/', expand=True)
df_f[['year','term']] = df_f['a'].str.split('_', expand=True)


df_f['year'] = df_f['year'].astype(int) # 년도 정수로 바꾸기
df_f['start_time_di'] = pd.to_datetime(df_f['start_time_di'], errors='coerce') #date로 바꾸기
df_f['last_event_di'] = pd.to_datetime(df_f['last_event_di'], errors='coerce') #date로 바꾸기

category_map = {
    'HarvardX/CB22x/2013_Spring': '문학',
    'HarvardX/CS50x/2012': '컴퓨터프로그래밍',
    'HarvardX/ER22x/2013_Spring': '인문학',
    'HarvardX/PH207x/2012_Fall': '의료서비스',
    'HarvardX/PH278x/2013_Spring': '환경과학',
    'MITx/14.73x/2013_Spring': '경제학',
    'MITx/2.01x/2013_Spring': '공학',
    'MITx/3.091x/2012_Fall': '화학',
    'MITx/3.091x/2013_Spring': '화학',
    'MITx/6.002x/2012_Fall': '공학',
    'MITx/6.002x/2013_Spring': '공학',
    'MITx/6.00x/2012_Fall': '컴퓨터프로그래밍',
    'MITx/6.00x/2013_Spring': '컴퓨터프로그래밍',
    'MITx/7.00x/2013_Spring': '생물학',
    'MITx/8.02x/2013_Spring': '물리학',
    'MITx/8.MReV/2013_Summer': '물리학'
}

df_f['course_category'] = df_f['course_id'].map(category_map)
df_f['last_event_di'] = pd.to_datetime(df_f['last_event_di'], errors='coerce') #date로 바꾸기
df_f['age'] = 2013 - df_f['yob']

df_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641138 entries, 0 to 641137
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   index              641138 non-null  int64
 1   course_id          641138 non-null  object
 2   userid_di          641138 non-null  object
 3   registered         641138 non-null  int64
 4   viewed             641138 non-null  int64
 5   explored           641138 non-null  int64
 6   certified          641138 non-null  int64
 7   final_cc_cname_di  641138 non-null  object
 8   loe_di             535130 non-null  object
 9   yob                544533 non-null  float64
 10  gender             554332 non-null  object
 11  grade              583738 non-null  float64
 12  start_time_di      641138 non-null  datetime64[ns]
 13  last_event_di      462184 non-null  datetime64[ns]
 14  nevents            441987 non-null  float64
 15  ndays_act          478395 non-null  float64
 16  nplay_video        183608 non-null  float64
 17  nchapters          382385 non-null  float64
 18  nforum_posts       641138 non-null  int64
 19  roles              0 non-null       float64
 20  incomplete_flag    100161 non-null  float64
 21  institution        641138 non-null  object
 22  course_code        641138 non-null  object
 23  a                  641138 non-null  object
 24  year               641138 non-null  int64
 25  term               471517 non-null  object
 26  course_category    641138 non-null  object
 27  age                544533 non-null  float64
dtypes: datetime64[ns](2), float64(9), int64(7), object(10)
memory usage: 137.0+ MB

In [43]:
df_f['nchapters'].value_counts()

nchapters
1.00     121837
2.00     110085
3.00      52296
4.00      24937
5.00      13838
6.00       8536
12.00      7987
7.00       6556
8.00       5009
9.00       4091
10.00      3598
18.00      3411
11.00      3258
16.00      2890
15.00      2684
13.00      2053
14.00      2021
17.00      1877
32.00       657
20.00       624
33.00       511
19.00       473
21.00       424
31.00       385
27.00       352
26.00       339
34.00       271
25.00       250
28.00       193
30.00       181
29.00       179
24.00       157
22.00       150
23.00       149
36.00        23
35.00        16
37.00        15
40.00        12
42.00        11
39.00        10
38.00         8
48.00         6
43.00         6
41.00         5
47.00         5
46.00         3
44.00         3
45.00         3
Name: count, dtype: int64

In [44]:
df_f['term'].value_counts()

term
Spring    298691
Fall      163349
Summer      9477
Name: count, dtype: int64

In [45]:
df_2012 = df_f.loc[(df_f['year'] == 2012) & (df_f['term'] == 'Fall')]

df_2012.loc[:,['start_time_di','year','term']]
df_2012.groupby(['year', 'start_time_di', 'term'])[['index']].count()

                         index
year start_time_di term
2012 2012-07-23    Fall      4
     2012-07-24    Fall   2553
     2012-07-25    Fall   1891
     2012-07-26    Fall   1244
     2012-07-27    Fall    925
...                        ...
     2013-09-03    Fall     47
     2013-09-04    Fall     42
     2013-09-05    Fall     56
     2013-09-06    Fall     51
     2013-09-07    Fall     24

[412 rows x 1 columns]

In [46]:
import pandas as pd
import numpy as np

# 날짜형 변환
df['start_time_di'] = pd.to_datetime(df['start_time_di'], errors='coerce')
df['last_event_di'] = pd.to_datetime(df['last_event_di'], errors='coerce')

# [파생] 전체기간(시작일 포함)
df['total_period_days'] = (df['last_event_di'] - df['start_time_di']).dt.days + 1

# 혹시 이상치로 0 이하가 나오면 결측 처리
df.loc[df['total_period_days'] <= 0, 'total_period_days'] = np.nan

# [파생] 전체기간 중 실제 활동 비율
df['active_day_ratio'] = df['ndays_act'] / df['total_period_days']

In [47]:
df[['start_time_di', 'last_event_di', 'ndays_act', 'total_period_days', 'active_day_ratio']].head()

  start_time_di last_event_di  ndays_act  total_period_days  active_day_ratio
0    2012-12-19    2013-11-17       9.00             334.00              0.03
1    2012-10-15           NaT       9.00                NaN               NaN
2    2013-02-08    2013-11-17      16.00             283.00              0.06
3    2012-09-17           NaT      16.00                NaN               NaN
4    2012-12-19           NaT      16.00                NaN               NaN

In [48]:
df.groupby('explored')[['ndays_act', 'total_period_days', 'active_day_ratio']].mean()
df.groupby('certified')[['ndays_act', 'total_period_days', 'active_day_ratio']].mean()

           ndays_act  total_period_days  active_day_ratio
certified
0               4.13              47.62              0.54
1              46.91             159.19              0.33

In [49]:
test_df = df[(df['explored'] == 0) & (df['certified'] == 1)]

test_df['loe_di'].value_counts()

loe_di
Secondary              246
Bachelor's             229
Master's                95
Less than Secondary     27
Doctorate                8
Name: count, dtype: int64

In [50]:
df_f.groupby(['course_code','year','term'])['explored'].agg(['mean'])

                         mean
course_code year term
14.73x      2013 Spring  0.11
2.01x       2013 Spring  0.10
3.091x      2012 Fall    0.06
            2013 Spring  0.02
6.002x      2012 Fall    0.07
            2013 Spring  0.04
6.00x       2012 Fall    0.06
            2013 Spring  0.05
7.00x       2013 Spring  0.07
8.02x       2013 Spring  0.06
8.MReV      2013 Summer  0.04
CB22x       2013 Spring  0.02
ER22x       2013 Spring  0.06
PH207x      2012 Fall    0.10
PH278x      2013 Spring  0.03

In [51]:
df_f.groupby(['course_code','year','term'])['certified'].agg(['mean'])

                         mean
course_code year term
14.73x      2013 Spring  0.07
2.01x       2013 Spring  0.04
3.091x      2012 Fall    0.04
            2013 Spring  0.02
6.002x      2012 Fall    0.04
            2013 Spring  0.03
6.00x       2012 Fall    0.04
            2013 Spring  0.02
7.00x       2013 Spring  0.04
8.02x       2013 Spring  0.03
8.MReV      2013 Summer  0.03
CB22x       2013 Spring  0.01
ER22x       2013 Spring  0.04
PH207x      2012 Fall    0.04
PH278x      2013 Spring  0.02